feature: create entity class and make doctrine mapping
AntoineGonzalez/knp-taste pull request #2
Opened 2022-09-06 16:30 UTC by AntoineGonzalez

Create entities, install doctrine and make entities mapping

2022-09-07 12:53 UTC, AntoineGonzalez commented
In this PR i have : 
- implements my entities class.
- install & configure doctrine
- write the doctrine mapping using xml format
- set up fixtures generation
- create users fixtures

2022-09-07 13:08 UTC, PedroTroller requested changes
Clairement, tu as créé des entités très complètes.... et avec plein de getters et setters qui ne servirons peut être à rien. Moi je pense que tu peut garder tes entitées mais tu les vides de leur propriétés pour le moemnt et tu les créra au moment où tu en aura besoin.

2022-09-07 13:08 UTC, PedroTroller commented on apps/backend/fixtures/fixtures.yml
> +      password: '\$2y\$10\$8N9rgJBZzhjqVKiXTUjXk.emOAfDYmBQQYOgWl4wvqCv7Nbk4tQ2e'
N'hesite pas à mettre un petit commentaire quand tu marques un hash comme ça en indiquant la string en clair qui correspond, le dev qui passera après toi sera très content ;)

2022-09-07 13:08 UTC, PedroTroller commented on apps/backend/src/Entity/Identicable.php
> +abstract class Identicable
Cette classe n'a pas de sens, tu commence à créer des choses compliquées dès les première lignes de codes.

2022-09-07 13:19 UTC, AntoineGonzalez commented on apps/backend/fixtures/fixtures.yml
> +      password: '\$2y\$10\$8N9rgJBZzhjqVKiXTUjXk.emOAfDYmBQQYOgWl4wvqCv7Nbk4tQ2e'
J'y ai pensé mais j'ai hésité et je ne l'ai pas mis, mb =)

2022-09-08 08:01 UTC, PedroTroller requested changes

2022-09-08 08:01 UTC, PedroTroller commented on apps/backend/src/Entity/User.php
> +        $this->applications = $applications;
Pas utile

2022-09-08 08:01 UTC, PedroTroller approved these changes

2022-09-08 08:05 UTC, merged